apiVersion: v1
kind: Secret
metadata:
  name: {{ include "probo.fullname" . }}
  labels:
    {{- include "probo.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  db-password: {{ include "probo.postgresql.password" . | quote }}

  # S3 credentials
  s3-access-key: {{ include "probo.s3.accessKeyId" . | quote }}
  s3-secret-key: {{ include "probo.s3.secretAccessKey" . | quote }}

  # Application secrets
  encryption-key: {{ .Values.probo.encryptionKey | required "probo.encryptionKey is required" | quote }}
  cookie-secret: {{ .Values.probo.auth.cookieSecret | required "probo.auth.cookieSecret is required" | quote }}
  password-pepper: {{ .Values.probo.auth.passwordPepper | required "probo.auth.passwordPepper is required" | quote }}
  trust-token-secret: {{ .Values.probo.trustAuth.tokenSecret | required "probo.trustAuth.tokenSecret is required" | quote }}

  # Optional SMTP credentials
  {{- if .Values.probo.mailer.smtp.user }}
  smtp-user: {{ .Values.probo.mailer.smtp.user | quote }}
  {{- end }}
  {{- if .Values.probo.mailer.smtp.password }}
  smtp-password: {{ .Values.probo.mailer.smtp.password | quote }}
  {{- end }}

  # Optional OpenAI API key
  {{- if .Values.probo.openai.apiKey }}
  openai-api-key: {{ .Values.probo.openai.apiKey | quote }}
  {{- end }}
