# Test values for local Helm chart testing
# DO NOT use these values in production!

# Probo application configuration
probo:
  hostname: "probo.local.test"
  encryptionKey: "dGVzdC1lbmNyeXB0aW9uLWtleS0zMi1ieXRlcw=="  # base64: test-encryption-key-32-bytes

  cors:
    allowedOrigins:
      - "http://localhost:5173"
      - "http://probo.local.test"

  auth:
    disableSignup: false
    cookieDomain: "probo.local.test"
    cookieSecret: "dGVzdC1jb29raWUtc2VjcmV0LTMyLWJ5dGVzcw=="  # base64: test-cookie-secret-32-bytes
    passwordPepper: "dGVzdC1wYXNzd29yZC1wZXBwZXItMzItYnl0ZXM="  # base64: test-password-pepper-32-bytes

  trustAuth:
    cookieDomain: "probo.local.test"
    tokenSecret: "dGVzdC10cnVzdC10b2tlbi1zZWNyZXQtMzItYnl0ZXM="  # base64: test-trust-token-secret-32-bytes

  mailer:
    smtp:
      addr: "mailhog:1025"
      tlsRequired: false

# PostgreSQL configuration
# Enable the included CloudNativePG cluster for testing
postgresql:
  # -- enabled included Postgres container for demo purposes only using cloudnative-pg
  enabled: true
  resources:
    limits:
      memory: "2Gi"
      ephemeral-storage: "50Gi"
  auth:
    postgresUser: postgres
    postgresPassword: probod
    database: probod
# S3 storage configuration
# Leave s3 section as defaults - MinIO will override when enabled
s3:
  region: "us-east-1"
  bucket: "probod"

# MinIO configuration
# Enable the included MinIO subchart for testing
minio:
  enabled: false

  # Bitnami MinIO subchart configuration (used when enabled=true)
  # See: https://github.com/bitnami/charts/tree/main/bitnami/minio
  mode: standalone
  primary:
    enabled: true
  auth:
    rootUser: "minio-admin"
    rootPassword: "minio-test-password"  # Change this for testing
  defaultBuckets: "probod"

# Enable Chrome for PDF generation
chrome:
  enabled: true

# Enable persistence for testing
persistence:
  enabled: true
  storageClass: "standard"
  size: 1Gi

# Resource limits for testing (smaller)
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
